---
- name: Update apt cache
  apt:
    update_cache: true
  become: true

- name: Install raspberry-pi base packages
  package: name="{{packages}}" state=latest
  become: true
  vars:
    packages:
      - dnsutils
      - raspberrypi-kernel-headers  # For compiling wireguard

#######################################
# Docker                              #
#######################################

- name: Check if docker installed
  ignore_errors: true
  register: docker_installed
  command: which docker

- name: Download Docker install script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: 0755
  when: docker_installed is failed

- name: Install Docker
  command: /tmp/get-docker.sh
  become: true
  when: docker_installed is failed

#######################################
# WireGuard                           #
#######################################

- name: Create src directory
  file: path=~/src state=directory mode=0755

- name: Download WireGuard source
  unarchive:
    src: https://git.zx2c4.com/WireGuard/snapshot/WireGuard-{{wireguard_version}}.tar.xz
    dest: ~/src
    creates: ~/src/WireGuard-{{wireguard_version}}
    remote_src: true
  register: wireguard_src

- name: Compile WireGuard
  command: make -j3  # Leave 1 core unused
  args:
    chdir: ~/src/WireGuard-{{wireguard_version}}/src
  when: wireguard_src is changed

- name: Install WireGuard
  command: make install
  args:
    chdir: ~pi/src/WireGuard-{{wireguard_version}}/src
  become: true
  when: wireguard_src is changed

- name: Restart WireGuard interface
  service:
    name: wg-quick@wg0
    state: restarted
  become: true
  when: wireguard_src is changed
