---
- name: Install packages
  package:
    name: "{{packages}}"
    state: present
  become: true

- name: Add local repository for AUR packages
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [craig]
      SigLevel = Optional TrustAll
      Server = file:///media/morty/aur-packages
  become: true

- name: Install AUR packages
  package:
    name: "{{aur_packages}}"
    state: present
  become: true

- name: Install system config
  copy: src="{{item.src}}" dest="{{item.dest}}" mode=0644 force=true
  become: true
  with_items:
    - {src: makepkg.conf, dest: /etc/makepkg.conf}

- name: Create pacman hooks directory
  file: path=/etc/pacman.d/hooks state=directory mode=0755
  become: true

- name: Install pacman hooks
  copy:
    src: "{{item}}.hook"
    dest: "/etc/pacman.d/hooks/{{item}}.hook"
    force: true
    mode: 0644
  become: true
  with_items:
    - sort-mirrors

- name: List unused dependency packages
  command: pacman -Qtdq
  ignore_errors: true
  register: orphans

  # TODO sysctl module?
  # TODO enable now, don't wait for reboot
- name: Enable unprivileged user namespaces
  lineinfile:
    line: 'kernel.unprivileged_userns_clone=1'
    path: /etc/sysctl.d/99-custom.conf
    create: true
  become: true

- name: Create Virtualbox images directory with No_COW
  file: path="{{vbox_dir}}" state=directory mode=0755 attributes=C

- name: Create docker-machine images directory with No_COW
  file:
    path: "~/.docker/machine/machines"
    state: directory
    mode: 0700
    attributes: C

- name: Set virtualbox images directory
  command: VBoxManage setproperty machinefolder {{vbox_dir}}

- name: Install WireGuard interface config
  copy:
    dest: /etc/wireguard/wg0.conf
    content: "{{wireguard_cfg}}"  # host_vars
    mode: 0600
  become: true

# prevent_headphone_hissing is specific to the Dell XPS 13
# (https://wiki.archlinux.org/index.php/Dell_XPS_13_(9360)#Continuous_hissing_sound_with_headphones)
#
# Check the Arch wiki and try removing it on new laptops to see if it's actually
# needed.
#
# Update Dec 2019: not needed.
# - name: Install user units
#   copy:
#     src: "{{item}}"
#     dest: "~/.config/systemd/user/{{item}}"
#   with_items:
#     - prevent_headphone_hissing.service

- name: Start user units
  systemd:
    name: "{{item}}"
    scope: user
    state: started
    enabled: true
  with_items:
    - nordvpnud.service
    # - prevent_headphone_hissing.service

- name: Install hardware-specific AUR packages
  package:
    name:
      - canon-pixma-mg2500-complete
    state: present
  become: true

#######################################
# Backup                              #
#######################################

# /etc/backup would be too generic. Couldn't be bothered to think of a better name.
- name: Create backup config directory
  file:
    path: /etc/craig-backup
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0700
  become: true

- name: Write backup config file
  copy:
    dest: /etc/craig-backup/env
    content: "{{restic_env}}"
    mode: 0600

- name: Mark directories to be ignored by backup
  file: path=~/{{item}}/.backupignore state=touch
  ignore_errors: true
  with_items:
    - .android
    - .ansible
    - .atom
    - .bosh
    - .bundle
    - .cache
    - .cargo
    - .cert
    - .circleci
    - .docker
    - .fontconfig
    - .gem
    - .glide
    - .gnome
    - .local
    - .minikube
    - .mozilla
    - .npm
    - .pki
    - .rubies
    - .rustup
    - .subversion
    - .terraform.d
    - .vagrant.d
    - .vscode
    - virtualbox_vms

- name: Install btrfs-snapshot files
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: "{{item.mode}}"
  with_items:
    - {src: btrfs-snapshot.sh, dest: /usr/bin/btrfs-snapshot, mode: "0755"}
    - {src: btrfs-snapshot.service, dest: /lib/systemd/system/btrfs-snapshot.service, mode: "0644"}
    - {src: btrfs-snapshot.timer, dest: /lib/systemd/system/btrfs-snapshot.timer, mode: "0644"}
  become: true

- name: Install craig-backup systemd units
  template:
    src: "craig-backup.{{item}}.j2"
    dest: "/lib/systemd/system/craig-backup.{{item}}"
  become: true
  with_items:
    - service
    - timer

- name: Start units
  service: name={{item}} state=started enabled=true
  become: true
  with_items:
    - btrfs-snapshot.timer
    - craig-backup.timer
    - logrotate.timer
    - nordvpnsd.service
    - org.cups.cupsd.service
    - pcscd.service

#######################################
# Cleanup                             #
#######################################

- name: Remove unused dependency packages
  shell: pacman -Rns --noconfirm $(pacman -Qtdq)
  become: true
  when: orphans is succeeded

- name: Clear pacman cache
  command: pacman -Sc --noconfirm
  become: true
