---
- tags: [archlinux-headless]
  hosts: all
  become_method: sudo
  tasks:
  - pacman: name={{item}}
    become: true
    with_items:
    - ack
    - ansible
    - asp
    - bind-tools
    - ctags
    - curl
    - devtools
    - git
    - go
    - hdparm
    - hexedit
    - htop
    - iotop
    - jq
    - lastpass-cli
    - linux-headers
    - lshw
    - lsof
    - mlocate
    - mtools
    - neovim
    - nfs-utils
    - openbsd-netcat
    - openssh
    - openvpn
    - postfix
    - python-neovim
    - python-pip
    - python2-neovim
    - reflector
    - ripgrep
    - ruby
    - rustup
    - shellcheck
    - smartmontools
    - stow
    - strace
    - tcpdump
    - terraform
    - the_silver_searcher
    - tmux
    - tree
    - vim
    - wget
    - whois
    - zsh

  - shell: sed -i "s/COMPRESSXZ=.*$/COMPRESSXZ=(xz -c -z --threads $(nproc) -)/g" /etc/makepkg.conf
    become: true

  - file: path=~/aur state=directory mode=0755
  - aur: name=aurutils user={{ansible_env.USER}}

  - file: path=/etc/pacman.d/hooks state=directory mode=0755
    become: true

  - copy: src="{{item.src}}" dest="{{item.dest}}" force=true mode=0644
    become: true
    with_items:
    - {src: "{{ansible_env.PWD}}/config/pacman-hooks/sort-mirrors.hook", dest: /etc/pacman.d/hooks/sort-mirrors.hook}

  - command: pacman -Qtdq
    ignore_errors: true
    register: orphans

  - shell: pacman -Rns --noconfirm $(pacman -Qtdq)
    become: true
    when: orphans|succeeded

  - command: pacman -Sc --noconfirm
    become: true
