tap 'caskroom/versions'
tap 'caskroom/fonts'
tap 'universal-ctags/universal-ctags'
tap 'gocardless/homebrew-taps'

cask 'aws-vault'
cask 'docker'
cask 'dropbox'
cask 'flycut'
cask 'font-inconsolata'
cask 'google-cloud-sdk'
cask 'iterm2-nightly'
cask 'keybase'
cask 'minikube'
cask 'postman'
cask 'shiftit'
cask 'slack'
cask 'vagrant'
cask 'virtualbox'

# TODO reenable with --HEAD
# brew 'universal-ctags'

brew 'ack'
brew 'awscli'
brew 'ansible'
brew 'bash'
brew 'bash-completion2'
brew 'chruby'
brew 'coreutils'
brew 'curl'
brew 'dep'
brew 'direnv'
brew 'docker'
brew 'docker-compose'
brew 'docker-machine'
brew 'git'
brew 'go'
brew 'gpg'
brew 'htop'
brew 'hub'
brew 'ipcalc'
brew 'jq'
brew 'mas'
brew 'neovim'
brew 'pinentry-mac' # for gpg-agent
brew 'postgresql'
brew 'pv'
brew 'pwgen'
brew 'redis'
brew 'ripgrep'
brew 'ruby-install'
brew 'rustup'
brew 'shellcheck'
brew 'smartmontools'
brew 'sshuttle'
brew 'stow'
brew 'terraform'
brew 'terraform-docs'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'ykpers'
brew 'zsh'
brew 'zsh-completions'

# GC
brew 'anu'

# Various libs needed to install gem native extensions
brew 'icu4c'
brew 'qt@5.5'
