---
- hosts: pc
  remote_user: craig
  vars:
    user: craig
    debs:
      chrome: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dropbox: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.02.12_amd64.deb
      ubuntu_tweak: https://launchpad.net/ubuntu-tweak/0.8.x/0.8.7/+download/ubuntu-tweak_0.8.7-1~trusty2_all.deb
      atom: https://atom.io/download/deb
      vagrant: https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
    git_apps:
      chruby: https://github.com/postmodern/chruby.git
      ruby-install:  https://github.com/postmodern/ruby-install.git
      direnv: https://github.com/direnv/direnv.git
      gnome-terminal-colors-monokai: https://github.com/pricco/gnome-terminal-colors-monokai.git
  tasks:
  - name: add apt repositories
    become: yes
    become_method: sudo
    apt_repository: repo={{ item }}
    with_items:
      - ppa:git-core/ppa
      - ppa:webupd8team/java
      - ppa:caffeine-developers/ppa
      - ppa:ansible/ansible
  - name: add virtualbox repository
    become: yes
    become_method: sudo
    lineinfile: dest=/etc/apt/sources.list line='deb http://download.virtualbox.org/virtualbox/debian vivid contrib'
  - name: add virtualbox repository key
    become: yes
    become_method: sudo
    apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc
  - name: update apt cache
    become: yes
    become_method: sudo
    apt: update_cache=yes
  - name: Accept Oracle license for Java
    become: yes
    become_method: sudo
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  - name: install packages
    become: yes
    become_method: sudo
    apt: name={{ item }} state=latest
    with_items:
      - alacarte
      - ack-grep
      - ansible
      - caffeine
      - clipit
      - curl
      - deluge
      - dkms
      - exuberant-ctags
      - fonts-inconsolata
      - git
      - gparted
      - htop
      - indicator-multiload
      - lm-sensors
      - make
      - mercurial
      - oracle-java8-installer
      - silversearcher-ag
      - tree
      - tmux
      - vim
      - vim-nox
      - virtualbox-5.0
      - vlc
      - wget
      - xclip
      - zsh
  - name: clone oh my zsh
    git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh
  - name: set zsh as default shell
    become: yes
    become_method: sudo
    user: name={{ user }} shell=/bin/zsh
  - name: clone home repo
    script: scripts/home.sh creates='/home/{{ user }}/.git'
  - name: download debs
    get_url: url={{ item.value }} dest=~/Downloads/{{ item.key }}.deb
    with_dict: "{{ debs }}"
  - name: install debs
    become: yes
    become_method: sudo
    apt: deb=/home/{{ user }}/Downloads/{{ item.key }}.deb
    with_dict: "{{ debs }}"
  - name: download go
    get_url: url=https://storage.googleapis.com/golang/go1.5.1.linux-amd64.tar.gz dest=~/Downloads/go.tar.gz
  - name: extract go
    unarchive: copy=no src=~/Downloads/go.tar.gz dest=~/Downloads creates=~/golang # yes, look at next step
  - name: move go
    command: mv ~/Downloads/go ~/golang creates=~/golang
  - name: clone luan vim config
    git: repo=https://github.com/luan/vimfiles.git dest=~/.vim
  - name: install luan vim config
    command: ~/.vim/install creates=~/.vimrc
  - name: install atom package sync
    command: apm install package-sync creates=~/.atom/packages/package-sync
  - name: make git-apps directory # TODO is this really necessary?
    command: mkdir -p ~/git-apps
  - name: clone git apps
    git: repo={{ item.value }} dest=~/git-apps/{{ item.key }}
    with_dict: "{{ git_apps }}"
  - name: install makeable git apps
    become: yes
    become_method: sudo
    command: make install chdir=/home/{{ user }}/git-apps/{{ item.name }} creates={{ item.creates }}
    with_items:
      - { name: 'chruby', creates: '/usr/local/share/chruby' }
      - { name: 'ruby-install', creates: '/usr/local/bin/ruby-install' }
  - name: install direnv
    become: yes
    become_method: sudo
    command: make install chdir=/home/{{ user }}/git-apps/direnv creates=/usr/local/bin/direnv
    environment:
      GOROOT: /home/{{ user }}/golang
      PATH: /home/{{ user }}/golang/bin:{{ ansible_env.PATH }}
  # Can't install ruby yet, involves interactive sudo
  # - name: install ruby
  #   command: ruby-install ruby 2.2.3 creates=~/.rubies/ruby-2.2.3/bin/ruby
  # Can't install this non-interactively
  # - name: monokai terminal theme
  #   command: ~/git-apps/gnome-terminal-colors-monokai/install.sh
