---
- hosts: pc
  remote_user: craig
  vars:
    user: craig
  tasks:
  - name: add apt repositories
    become: yes
    become_method: sudo
    apt_repository: repo={{ item }}
    with_items:
      - ppa:git-core/ppa
      - ppa:webupd8team/java
      - ppa:caffeine-developers/ppa
  - name: update apt cache
    become: yes
    become_method: sudo
    apt: update_cache=yes
  - name: Accept Oracle license for Java
    become: yes
    become_method: sudo
    debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  - name: install packages
    become: yes
    become_method: sudo
    apt: name={{ item }} state=latest
    with_items:
      - alacarte
      - ack-grep
      - caffeine
      - clipit
      - curl
      - deluge
      - fonts-inconsolata
      - git
      - gparted
      - htop
      - indicator-multiload
      - lm-sensors
      - make
      - mercurial
      - oracle-java8-installer
      - tree
      - tmux
      - vim
      - vlc
      - wget
      - xclip
      - zsh
  - name: clone oh my zsh
    git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/{{ user }}/.oh-my-zsh
  - name: set zsh as default shell
    become: yes
    become_method: sudo
    user: name={{ user }} shell=/bin/zsh
  - name: clone home repo
    script: scripts/home.sh creates='/home/{{ user }}/.git'
  - name: ubuntu tweak download
    get_url: url=https://launchpad.net/ubuntu-tweak/0.8.x/0.8.7/+download/ubuntu-tweak_0.8.7-1~trusty2_all.deb dest=~/Downloads/ubuntu-tweak.deb
  - name: install ubuntu tweak
    become: yes
    become_method: sudo
    apt: deb=/home/{{ user }}/Downloads/ubuntu-tweak.deb
