#!/usr/bin/env ruby
# frozen_string_literal: true

# TODO: write this in Python, as that Ruby may not be present on first run

require "json"
require "socket"

host = Socket.gethostname

groups = {
  "craig-laptop" => ["archlinux_pcs"],
  "craigf-gitlab.local" => ["macs"],
}

hosts = groups.fetch(host).map do |group|
  [
    group,
    {
      hosts: [host],
      vars: {
        ansible_connection: "local",
        ansible_user: "craig",
      },
    },
  ]
end.to_h

puts hosts.to_json
