---
- tags: [desktop, laptop]
  hosts: all
  become_method: sudo
  vars:
    vbox_dir: ~/virtualbox_vms
  tasks:
  - pacman: name={{item}}
    become: true
    with_items:
    - ack
    - ansible
    - asp
    - atom
    - bind-tools
    - crda
    - ctags
    - curl
    - deluge
    - devtools
    - docker
    - docker-machine
    - firefox
    - git
    - gnome-tweak-tool
    - gnupg
    - go
    - gparted
    - hdparm
    - hexedit
    - htop
    - jq
    - lastpass-cli
    - libreoffice-still
    - linux-headers
    - lshw
    - lsof
    - mlocate
    - mtools
    - neovim
    - networkmanager-openvpn
    - nfs-utils
    - openssh
    - openvpn
    - postfix
    - powertop
    - pygtk
    - python-neovim
    - python-pip
    - python2-neovim
    - qt4
    - reflector
    - ripgrep
    - ruby
    - rustup
    - seahorse
    - shellcheck
    - smartmontools
    - strace
    - terraform
    - the_silver_searcher
    - tmux
    - tree
    - vagrant
    - virtualbox
    - virtualbox-host-dkms
    - vlc
    - wget
    - whois
    - xclip
    - zsh

  - command: rustup toolchain install stable
  - command: rustup default stable

  - user: name={{ ansible_env.USER }} shell=/usr/bin/zsh
    become: true

  - git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

  - git: repo=https://github.com/luan/vimfiles dest=~/.vim

  - git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

  - file: src={{item.src}} dest={{item.dest}} state=link force=true
    with_items:
    - {src: "{{ansible_env.PWD}}/config/zshrc", dest: ~/.zshrc}
    - {src: "{{ansible_env.PWD}}/config/tmux.conf", dest: ~/.tmux.conf}
    - {src: "{{ansible_env.PWD}}/config/gitconfig", dest: ~/.gitconfig}
    - {src: "{{ansible_env.PWD}}/config/vimrc.local.plugins", dest: ~/.vimrc.local.plugins}

  - shell: sed -i "s/COMPRESSXZ=.*$/COMPRESSXZ=(xz -c -z --threads $(nproc) -)/g" /etc/makepkg.conf
    become: true

  - file: path=~/aur state=directory mode=0755

  - aur: name={{item}} user={{ansible_env.USER}}
    with_items:
    - cower
    - pacaur

  - pacaur: name={{item}} state=present
    become: true
    with_items:
    - aurvote
    - bosh-cli
    - caffeine-ng
    - chruby
    - clipit
    - cloudfoundry-cli
    - direnv
    - dropbox
    - gnome-shell-extension-pixel-saver
    - gnome-shell-extension-topicons-plus-git
    - google-chrome
    - gotty
    - nautilus-dropbox # GNOME/Files integration
    - ngrok
    - ruby-install
    - skypeforlinux-bin
    - slack-desktop
    - tmate
    - ttf-google-fonts-git
    - visual-studio-code
    - zoom

  - file: path=/etc/pacman.d/hooks state=directory mode=0755
    become: true

  - copy: src="{{item.src}}" dest="{{item.dest}}" force=true mode=0644
    become: true
    with_items:
    - {src: "{{ansible_env.PWD}}/config/pacman-hooks/sort-mirrors.hook", dest: /etc/pacman.d/hooks/sort-mirrors.hook}

  - command: pacman -Qtdq
    ignore_errors: true
    register: orphans

  - shell: pacman -Rns --noconfirm $(pacman -Qtdq)
    become: true
    when: orphans|succeeded

  - command: pacman -Sc --noconfirm
    become: true

  - command: "{{ansible_env.PWD}}/scripts/clean-pacaur-cache.sh"

  - file: path="{{vbox_dir}}" state=directory mode=0755 attributes=C
  - command: VBoxManage setproperty machinefolder {{vbox_dir}}

- tags: [desktop]
  hosts: all
  tasks:
  - pacaur: name={{item}} state=present
    become: true
    with_items:
    - plex-media-server
    - google-musicmanager
