---
- tags: [desktop, laptop]
  hosts: all
  become_method: sudo
  tasks:
  - pacman: name={{item}}
    become: true
    with_items:
    - ack
    - ansible
    - atom
    - ctags
    - deluge
    - devtools
    - firefox
    - git
    - gnome-tweak-tool
    - go
    - hdparm
    - htop
    - jq
    - lastpass-cli
    - libreoffice-still
    - linux-headers
    - lshw
    - mlocate
    - neovim
    - networkmanager-openvpn
    - openssh
    - openvpn
    - pygtk
    - python-neovim
    - python2-neovim
    - qt4
    - shellcheck
    - smartmontools
    - terraform
    - the_silver_searcher
    - tmux
    - tree
    - vagrant
    - virtualbox
    - vlc
    - wget
    - xclip
    - zsh

  - git: repo=https://github.com/luan/vimfiles dest=~/.vim

  - git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

  - command: updatedb
    become: true
