---
- tags: [desktop, laptop]
  hosts: all
  become_method: sudo
  tasks:
  - pacman: name={{item}}
    become: true
    with_items:
    - ack
    - ansible
    - asp
    - atom
    - ctags
    - deluge
    - devtools
    - firefox
    - git
    - gnome-tweak-tool
    - gnupg
    - go
    - gparted
    - hdparm
    - htop
    - jq
    - lastpass-cli
    - libreoffice-still
    - linux-headers
    - lshw
    - mlocate
    - mtools
    - neovim
    - networkmanager-openvpn
    - openssh
    - openvpn
    - pygtk
    - python-neovim
    - python2-neovim
    - qt4
    - shellcheck
    - smartmontools
    - terraform
    - the_silver_searcher
    - tmux
    - tree
    - vagrant
    - virtualbox
    - vlc
    - wget
    - xclip
    - zsh

  - user: name={{ ansible_env.USER }} shell=/usr/bin/zsh
    become: true

  - git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

  - git: repo=https://github.com/luan/vimfiles dest=~/.vim

  - git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

  - file: src={{item.src}} dest={{item.dest}} state=link force=true
    with_items:
    - {src: "{{ansible_env.PWD}}/config/zshrc", dest: ~/.zshrc}
    - {src: "{{ansible_env.PWD}}/config/tmux.conf", dest: ~/.tmux.conf}
    - {src: "{{ansible_env.PWD}}/config/gitconfig", dest: ~/.gitconfig}
    - {src: "{{ansible_env.PWD}}/config/vimrc.local.plugins", dest: ~/.vimrc.local.plugins}

  - command: updatedb
    become: true

  - file: path=~/aur state=directory mode=0755

  - aur: name={{item}} user={{ansible_env.USER}}
    with_items:
    - cower
    - pacaur

  - pacaur: name={{item}} state=present
    become: yes
    with_items:
    - aurvote
    - bosh-cli
    - caffeine-ng
    - chruby
    - clipit
    - direnv
    - dropbox
    - gnome-shell-extension-topicons-plus-git
    - google-chrome
    - ruby-install
    - ttf-google-fonts-git

  - command: pacman -Sc
    become: yes

  - command: "{{ansible_env.PWD}}/scripts/clean-pacaur-cache.sh"

- tags: [desktop]
  hosts: all
  tasks:
  - file: src={{ansible_env.PWD}}/config/zshrc_desktop dest=~/.zshrc_machine_specific state=link force=true

  - pacaur: name=plex-media-server state=present
    become: yes
