---
- hosts: raspberry_pi
  roles:
    - raspberry-preamble
    - wireguard-peer
- hosts: all
  roles:
    - server-common
    - ssh-server
- hosts: raspberry_pi
  roles:
    - pi-hole
- hosts: media-servers
  roles:
    - archlinux-mediaserver
