---
# TODO move printer to all Arch PCs
- name: Install AUR packages
  package:
    name:
      - canon-pixma-mg2500-complete  # Hardware-specific
    state: present
  become: true

# TODO all Arch PCs
- name: Start printer service
  service: name=org.cups.cupsd.service state=started enabled=true
  become: true
