# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.vm.hostname = "bojack"
  config.vm.synced_folder "~", "/host/home"

  config.vm.network "forwarded_port", guest: 8000, host: 18000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8001, host: 18001, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8002, host: 18002, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8003, host: 18003, host_ip: "127.0.0.1"

  config.vm.provider "virtualbox" do |vm|
    vm.name = "bojack"
    vm.memory = 4096
    vm.cpus = 4
    # TODO does this work?
    vm.customize ["modifyvm", :id, "--uartmode1", "file", "#{File.dirname(__FILE__)}/bojack-console.log"]
  end

  config.vm.provision "shell", path: "provision.sh"

  config.ssh.forward_agent = true
end
