# vi: syntax=ruby

brew 'ansible'
brew 'bash'
brew 'curl'
brew 'direnv'
brew 'docker'
brew 'docker-machine'
brew 'fzf'
brew 'git'
brew 'gpg'
brew 'htop'
brew 'jq'
brew 'neovim'
brew 'pwgen'
brew 'python'
brew 'ripgrep'
brew 'shellcheck'
brew 'stow'
brew 'terraform'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'  # TODO used?

tap 'universal-ctags/universal-ctags'
brew 'universal-ctags', args: ['HEAD']

# gnutils
brew 'coreutils'
brew 'findutils'
brew 'gawk'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'grep'

# Ruby
brew 'chruby'
brew 'ruby-install'

# casks
cask '1password'
cask 'flycut'
cask 'google-chrome'
cask 'gpg-suite'
cask 'karabiner-elements'
cask 'shiftit'
cask 'signal'
cask 'slack'
cask 'vagrant'
cask 'virtualbox'
cask 'whatsapp'
cask 'zoomus'

tap 'homebrew/cask-fonts'
cask 'font-inconsolata'

# App store - TODO automate with mas when that works
# Todoist
