# vi: syntax=ruby

brew 'ansible'
brew 'azure-cli'
brew 'bash'
brew 'cmake'
brew 'curl'
brew 'direnv'
brew 'docker'
brew 'docker-machine'
brew 'fzf'
brew 'git'
brew 'gpg'
brew 'graphicsmagick'
brew 'htop'
brew 'jq'
brew 'libiconv'
brew 'make'
brew 'neovim'
brew 'openssl'
brew 'pidof'
brew 'pinentry-mac'
brew 'pkg-config'
brew 'postgresql@9.6'  # TODO: Manual: `brew pin postgresql@9.6`
brew 'pwgen'
brew 'python'
brew 're2'
brew 'redis'
brew 'restic'
brew 'ripgrep'
brew 'runit'
brew 'shellcheck'
brew 'stow'
brew 'tfenv'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'yamllint'
brew 'yarn', args: ['ignore-dependencies']
brew 'ykman'
brew 'zsh'
brew 'zsh-completions'  # TODO used?

tap 'universal-ctags/universal-ctags'
brew 'universal-ctags', args: ['HEAD']

tap 'jeantil/autokbisw'
brew 'autokbisw' # restart_service: true  # TODO not yet working properly - keeps switching back to US

# gnutils
brew 'coreutils'
brew 'findutils'
brew 'gawk'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'grep'

# Ruby
brew 'chruby'
brew 'ruby-install'

# casks
cask '1password'
cask 'chromedriver'
cask 'flycut'
cask 'google-chrome'
cask 'google-cloud-sdk'
# cask 'gswitch'  # TODO doesn't behave properly on wake. Apparently unsafe mode fixes
cask 'karabiner-elements'
cask 'keybase'
cask 'shiftit'
cask 'signal'
cask 'slack'
cask 'vagrant'
cask 'virtualbox'
cask 'whatsapp'
cask 'zoomus'

tap 'homebrew/cask-fonts'
cask 'font-inconsolata'

# TODO device not recognised
# tap 'homebrew/cask-drivers'
# cask 'logitech-control-center'

# App store - TODO automate with mas when that works
# Todoist
