---
- name: add tlp apt repository
  become: yes
  become_method: sudo
  apt_repository: repo=ppa:linrunner/tlp

- name: install laptop packages
  become: yes
  become_method: sudo
  apt: name={{ item }} state=latest
  with_items:
    - tlp
    - xbacklight
