---
- name: Allow zsh to be used as a login shell
  lineinfile:
    path: /etc/shells
    line: "{{zsh_path}}"
  become: true

- command: brew bundle --no-lock --file macos/common.Brewfile
- command: brew bundle --no-lock --file macos/{{inventory_hostname}}.Brewfile
