---
- name: Install WireGuard interface config
  copy:
    dest: /etc/wireguard/wg0.conf
    content: "{{wireguard_cfg}}"  # host_vars
    mode: 0600
  become: true
  register: wireguard_interface_config

- name: Start and enable WireGuard interface
  service:
    name: wg-quick@wg0
    state: started
    enabled: true
  become: true

- name: Restart WireGuard interface
  service:
    name: wg-quick@wg0
    state: restarted
  become: true
  when: wireguard_interface_config is changed
