---
- name: archlinux-headless
  tags: [archlinux-headless]
  hosts: all
  become_method: sudo
  tasks:
  - name: Install pacman packages
    become: true
    pacman:
      name:
        - ack
        - ansible
        - asp
        - bind-tools
        - ctags
        - curl
        - dep
        - devtools
        - docker
        - fzf
        - git
        - go-pie
        - hdparm
        - hexedit
        - htop
        - hub
        - iotop
        - jq
        - lastpass-cli
        - linux-headers
        - lshw
        - lsof
        - mlocate
        - mtools
        - neovim
        - nfs-utils
        - openbsd-netcat
        - openssh
        - openvpn
        - pacman-contrib
        - pigz
        - postfix
        - python-neovim
        - python-pip
        - python2-neovim
        - reflector
        - restic
        - ripgrep
        - ruby
        - rustup
        - shellcheck
        - smartmontools
        - sshuttle
        - stow
        - strace
        - tcpdump
        - terraform
        - the_silver_searcher
        - tmux
        - tree
        - vim
        - wget
        - whois
        - zsh
        - zsh-completions

  - name: Install AUR packages
    become: true
    pacman:
      name:
        - aurutils
        - aurvote
        - chruby
        - cower
        - direnv
        # - google-drive-ocamlfuse  # TODO re-enable when compilation fixed
        - gotty
        - kubectl-bin
        - kubernetes-helm-bin
        - ngrok
        - ruby-install
        - tmate
        - yamllint

  - name: Configure makepkg to use all cores
    shell: |
      sed -i "s/COMPRESSXZ=.*$/COMPRESSXZ=(xz -c -z --threads $(nproc) -)/g" \
        /etc/makepkg.conf
    become: true

  - name: Create pacman hooks directory
    file: path=/etc/pacman.d/hooks state=directory mode=0755
    become: true

  - name: Install pacman hooks
    copy:
      src: "{{ansible_env.PWD}}/../config/pacman-hooks/{{item}}.hook"
      dest: "/etc/pacman.d/hooks/{{item}}.hook"
      force: true
      mode: 0644
    become: true
    with_items:
      - alacritty-config-upgrade
      - sort-mirrors

  - name: List unused dependency packages
    command: pacman -Qtdq
    ignore_errors: true
    register: orphans

  - name: Remove unused dependency packages
    shell: pacman -Rns --noconfirm $(pacman -Qtdq)
    become: true
    when: orphans is succeeded

  - name: Clear pacman cache
    command: pacman -Sc --noconfirm
    become: true

  - name: Enable unprivileged user namespaces
    lineinfile:
      line: 'kernel.unprivileged_userns_clone=1'
      path: /etc/sysctl.d/99-custom.conf
      create: true
    become: true
