---
- tags: [archlinux-media-server]
  hosts: all
  become_method: sudo
  tasks:
    - name: Install pacman packages
      become: true
      pacman:
        name:
          - transmission-cli

    - name: Install AUR packages
      become: true
      pacman:
        name:
          - canon-pixma-mg2500-complete  # Hardware-specific
          - networkmanager-vpn-web-ui
          - plex-media-server
