---
- name: add apt repositories
  become: yes
  become_method: sudo
  apt_repository: repo={{ item }}
  with_items:
    - ppa:git-core/ppa
    - ppa:webupd8team/java
    - ppa:webupd8team/atom

- name: add virtualbox repository
  become: yes
  become_method: sudo
  lineinfile: dest=/etc/apt/sources.list line='deb http://download.virtualbox.org/virtualbox/debian xenial contrib'

- name: add virtualbox repository key
  become: yes
  become_method: sudo
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: update apt cache
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: Accept Oracle license for Java
  become: yes
  become_method: sudo
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install packages
  become: yes
  become_method: sudo
  apt: name={{ item }} state=latest
  with_items:
    - alacarte
    - ack-grep
    - atom
    - caffeine
    - clipit
    - curl
    - deluge
    - dkms
    - exuberant-ctags
    - fonts-inconsolata
    - git
    - gparted
    - htop
    - indicator-multiload
    - lm-sensors
    - make
    - mercurial
    - network-manager-openvpn-gnome
    - oracle-java8-installer
    - redshift-gtk
    - silversearcher-ag
    - tree
    - tmux
    - unity-tweak-tool
    - vim
    - vim-nox
    - virtualbox-5.0
    - vlc
    - wget
    - xclip
    - zsh
    # For lastpass CLI
    - openssl
    - libcurl4-openssl-dev
    - libxml2
    - libssl-dev
    - libxml2-dev
    - pinentry-curses

- name: clone oh my zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

- name: set zsh as default shell
  become: yes
  become_method: sudo
  user: name={{ user }} shell=/bin/zsh

- name: clone home repo
  script: home.sh creates='/home/{{ user }}/.git'

- name: create downloads directory
  command: mkdir -p ~/Downloads/ansible-home-files

- name: download vagrant
  get_url: url=https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_x86_64.deb dest=~/Downloads/ansible-home-files/vagrant.deb

- name: install vagrant
  become: yes
  become_method: sudo
  apt: deb=/home/{{ user }}/Downloads/ansible-home-files/vagrant.deb

# Dropbox deb adds its own PPA, trying to update the deb package using apt module will fail
- name: check dropbox installed
  command: which dropbox
  register: dropbox_installed
  failed_when: dropbox_installed.rc > 1

- name: download dropbox
  get_url: url=https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb dest=~/Downloads/ansible-home-files/dropbox.deb
  when: dropbox_installed.rc != 0

- name: install dropbox
  become: yes
  become_method: sudo
  apt: deb=/home/{{ user }}/Downloads/ansible-home-files/dropbox.deb
  when: dropbox_installed.rc != 0

# Chrome deb adds its own PPA, trying to update the deb package using apt module will fail
- name: check chrome installed
  command: which google-chrome
  register: chrome_installed
  failed_when: chrome_installed.rc > 1

- name: download chrome
  get_url: url=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb dest=~/Downloads/ansible-home-files/chrome.deb
  when: chrome_installed.rc != 0

- name: install chrome
  become: yes
  become_method: sudo
  apt: deb=/home/{{ user }}/Downloads/ansible-home-files/chrome.deb
  when: chrome_installed.rc != 0

- name: download go
  get_url: url=https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz dest=~/Downloads/ansible-home-files/go.tar.gz

- name: extract go
  unarchive: copy=no src=~/Downloads/ansible-home-files/go.tar.gz dest=/usr/local creates=/usr/local/go

- name: clone luan vim config
  git: repo=https://github.com/luan/vimfiles.git dest=~/.vim

- name: install luan vim config
  command: ~/.vim/install chdir=~/.vim

- name: install atom package sync
  command: apm install package-sync

- name: make git-apps directory
  command: mkdir -p ~/git-apps

- name: clone git apps
  git: repo={{ item.value }} dest=~/git-apps/{{ item.key }}
  with_dict: "{{ git_apps }}"

- name: install makeable git apps
  become: yes
  become_method: sudo
  command: make install chdir=/home/{{ user }}/git-apps/{{ item.name }}
  with_items:
    - { name: 'chruby' }
    - { name: 'ruby-install' }
    - { name: 'lastpass-cli' }
    - { name: 'direnv' }
  environment:
    PATH: /usr/local/go/bin:{{ ansible_env.PATH }}

- name: download docker install script
  get_url: url=https://get.docker.com dest=~/Downloads/ansible-home-files/docker.sh

- name: make docker install script executable
  file: path=~/Downloads/ansible-home-files/docker.sh mode=0755

- name: install docker
  become: yes
  become_method: sudo
  command: /home/{{ user }}/Downloads/ansible-home-files/docker.sh creates=/usr/bin/docker
