---
- name: chsh to zsh
  user:
    name: "{{ansible_user}}"
    shell: "{{zsh_path}}"
  become: true

# Some of these are pre-reqs for later steps, and some are just there to stop
# GNU Stow from creating a symlink for the directory, forcing it to create ones
# for individual files instead.
- name: Create Directories
  file: path={{item}} state=directory mode=0755
  with_items:
    - ~/.ssh
    - ~/.bundle
    - ~/.config/kitty
    - ~/.config/nvim
    - ~/.local/share/nvim/site/autoload
    - ~/bin
    - ~/languages/go/{{go_version}}

- name: Create restricted directories
  file: path={{item}} state=directory mode=0700
  with_items:
    - ~/.gdfuse/default
    - ~/.ssh/master-sockets

- name: Install Go
  unarchive:
    src: https://dl.google.com/go/go{{go_version}}.{{ansible_facts['system'].lower()}}-amd64.tar.gz
    dest: "~/languages/go/{{go_version}}"
    creates: ~/languages/go/{{go_version}}/go
    remote_src: true

- name: Install config
  command: stow -t ~ home chdir={{ansible_env.PWD}}/config

- name: Install OS-specific config
  command: stow -t ~ home chdir={{ansible_env.PWD}}/config/os_specific/{{ansible_facts['system']}}

- name: Install machine-specific config
  command: stow -t ~ home chdir={{ansible_env.PWD}}/config/machine_specific/{{ansible_facts['hostname']}}

- name: Install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

- name: Install custom oh-my-zsh plugins
  git: repo="{{item.repo}}" dest="~/.oh-my-zsh/custom/plugins/{{item.name}}"
  with_items:
    - {name: zsh-nvm, repo: "https://github.com/lukechilds/zsh-nvm"}

- name: Install tmux plugin manager
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

  # We must install plugins before updating them
  # https://github.com/tmux-plugins/tpm/issues/137
- name: Install tmux plugins
  command: ~/.tmux/plugins/tpm/bin/install_plugins

- name: Update tmux plugins
  command: ~/.tmux/plugins/tpm/bin/update_plugins all

- name: Install vim-plug
  get_url:
    dest: ~/.local/share/nvim/site/autoload
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Install vim plugins
  command: nvim +PlugClean! +PlugUpdate +qa

# TODO: re-enable rust when rustup itself is bootstrapped by ansible
# - name: Install Stable Rust
#   command: rustup toolchain install stable
#
# - name: Set default rust to stable
#   command: rustup default stable
