---
- name: Install packages
  become: true
  package:
    name:
      - transmission-cli
    state: present

- name: Install AUR packages
  become: true
  package:
    name:
      - canon-pixma-mg2500-complete  # Hardware-specific
      - networkmanager-vpn-web-ui
      - plex-media-server
    state: present

# TODO enable services
