---
- name: archlinux-gnome
  tags: [archlinux-gnome]
  hosts: all
  become_method: sudo
  vars:
    vbox_dir: ~/virtualbox_vms
  tasks:
    - name: Install pacman packages
      become: true
      pacman:
        name:
          - alacritty
          - atom
          - crda
          - deluge
          - docker-machine
          - firefox
          - gnome-tweaks
          - gparted
          - kitty
          - libreoffice-still
          - networkmanager-openvpn
          - powertop
          - pygtk
          - qt4
          - seahorse
          - vagrant
          - virtualbox
          - virtualbox-host-modules-arch
          - vlc

    - name: Install AUR packages
      become: true
      pacman:
        name:
          # TODO caffeine won't start currently
          - caffeine-ng
          - clipit
          # TODO re-enable after https://github.com/deadalnix/pixel-saver/issues/177 merged.
          # Manually delete /usr/share/gnome-shell/extensions/pixel-saver@deadalnix.me first
          # - gnome-shell-extension-pixel-saver
          - gnome-shell-extension-topicons-plus-git
          - google-musicmanager
          - google-chrome
          - keybase-bin
          - minikube-bin
          - popcorntime
          - qtwebkit-bin  # Dependency of google-musicmanager. provides qtwebkit, which takes hours to compile
          - skypeforlinux-preview-bin
          - slack-desktop
          - ttf-google-fonts-git
          - visual-studio-code-bin
          - zoom

    - name: Create Virtualbox images directory with No_COW
      file: path="{{vbox_dir}}" state=directory mode=0755 attributes=C

    - name: Create docker-machine images directory with No_COW
      file:
        path: "~/.docker/machine/machines"
        state: directory
        mode: 0700
        attributes: C

    - name: Set virtualbox images directory
      command: VBoxManage setproperty machinefolder {{vbox_dir}}
