---
- name: common-headless
  tags: [common-headless]
  hosts: all
  become_method: sudo
  tasks:
  - name: Change shell to zsh
    user: name={{ ansible_env.USER }} shell=/usr/bin/zsh
    become: true

  - name: Create Go directory
    file: path=~/languages/go/1.11 state=directory mode=0755

  - name: Install Go
    unarchive:
      src: https://dl.google.com/go/go1.11.linux-amd64.tar.gz
      dest: ~/languages/go/1.11
      creates: ~/languages/go/1.11/go
      remote_src: true

  - name: Install config symlinks
    command: stow -t ~ home chdir={{ansible_env.PWD}}/../config

  - name: Install oh-my-zsh
    git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

  - name: Install tmux plugin manager
    git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

    # We must install plugins before updating them
    # https://github.com/tmux-plugins/tpm/issues/137
  - name: Install tmux plugins
    command: ~/.tmux/plugins/tpm/bin/install_plugins

  - name: Update tmux plugins
    command: ~/.tmux/plugins/tpm/bin/update_plugins all

  - name: Create vim autoload directory
    file: path=~/.local/share/nvim/site/autoload state=directory mode=0755

  - name: Install vim-plug
    get_url:
      dest: ~/.local/share/nvim/site/autoload
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  - name: Install vim plugins
    command: nvim +PlugClean! +PlugUpdate +qa

  - name: Install Stable Rust
    command: rustup toolchain install stable

  - name: Set default rust to stable
    command: rustup default stable
