---
- name: Install packages
  become: true
  package:
    name:
      - transmission-cli
    state: present

- name: Install AUR packages
  become: true
  package:
    name:
      - networkmanager-vpn-web-ui
      - plex-media-server
    state: present

# TODO services and config for: nfs, samba, transmission, plex, nm-vpn-webui
