---
git_apps:
  chruby: https://github.com/postmodern/chruby.git
  ruby-install:  https://github.com/postmodern/ruby-install.git
  direnv: https://github.com/direnv/direnv.git
  lastpass-cli: https://github.com/lastpass/lastpass-cli.git
